baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Ode to the Giants'
enableRobotsTXT = true

# Enable RSS feeds
disableRSS = false
disableKinds = []

[outputFormats]
  [outputFormats.RSS]
    mediaType = "application/rss+xml"
    baseName = "index"
    isPlainText = false
    notAlternative = true

[outputs]
  section = ["HTML", "RSS"]
  home = ["HTML", "RSS"]

[params]
  description = 'Personal website and blog of a passionate developer exploring technology, programming, and innovation'
  email = 'webmaster@odetothegiants.com'

[caches]
  [caches.images]
    dir = ':cacheDir/images'

[menu]
  [[menu.main]]
    name = 'Home'
    pageRef = '/'
    weight = 10
  [[menu.main]]
    name = 'Posts'
    pageRef = '/posts'
    weight = 20
  [[menu.main]]
    name = 'Showcase'
    pageRef = '/showcase'
    weight = 30
  [[menu.main]]
    name = 'References'
    pageRef = '/references'
    weight = 40
